"""Add chat_session_id column to chat_messages table

Revision ID: e255b572df2a
Revises: 
Create Date: 2025-04-05 22:47:10.829744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e255b572df2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('chat_session_id', sa.String(), nullable=False))
    op.drop_column('chat_messages', 'session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chat_messages', 'chat_session_id')
    # ### end Alembic commands ###
